### ISSUE TITLE
The FAW can fill up a system's harddrive, making SSH access / fixing the issue difficult

### ISSUE THREAD

**Issue by wwoods** [GaloisInc/FAW#98]
A parser that produces very large stdout/stderr can lead to this. How might we reasonably mitigate this? Should the FAW stop processing new files with less than X disk space left?

**Comment by caleblf** [comment]
I'm putting together a solution. Per our offline discussions, at least for now, the FAW should refuse to parse files when the disks (root and DB) are dangerously close to full. These parse jobs will be treated as errors so the FAW will retry them later, when there may be enough space. I'll make sure such errors are displayed on the frontend so the user knows what's going on.
